name: tp1_taller_ledger
services:

  ledger_app:
    build: .
    image: ledger_app:latest
    container_name: ledger_app_container
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger_db
      DB_HOST: db
      MIX_ENV: prod
      DATABASE_URL: "ecto://postgres:postgres@db:5432/ledger_db"
    command: tail -f /dev/null
    restart: always         
    stdin_open: true
    tty: true
    networks:
      - network



  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - network

  ledger_migrate:
    build: .
    image: ledger_app:latest
    container_name: ledger_migrate_container
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIX_ENV: ${MIX_ENV}
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    volumes:
      - .:/app
    working_dir: /app
    command: mix ecto.migrate
    networks:
      - network
    restart: "no"

volumes:
  db_data:

networks:
  network:
    driver: bridge
