name: tp1_taller_ledger
services:

  ledger_app:
    build: .
    image: ledger_app:${APP_VERSION}
    container_name: ledger_app_container
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIX_ENV: ${MIX_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: tail -f /dev/null
    restart: always         
    stdin_open: true
    tty: true
    networks:
      - default

  ledger_migrate:
    build: .
    image: ledger_app:${APP_VERSION}
    container_name: ledger_migrate_container
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIX_ENV: ${MIX_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app
    working_dir: /app
    command: mix ecto.migrate
    networks:
      - default
    restart: "no"

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    name: ${NETWORK}
    driver: bridge

