name: tp1_taller_ledger_dev
services:
  ledger_app:
    build: .
    image: ledger_app_dev:latest
    container_name: ledger_app_container_dev
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIX_ENV: ${MIX_ENV}
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    volumes:
      - ${LEDGER_DATA_PATH}:/ledger-container/priv/data
    command: tail -f /dev/null
    networks:
      - network_dev

  ledger_migrate:
    build: .
    image: ledger_app_dev:latest
    container_name: ledger_migrate_container_dev
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIX_ENV: ${MIX_ENV}
      DATABASE_URL: "ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    volumes:
      - .:/app
    working_dir: /app
    command: mix ecto.migrate
    networks:
      - network_dev
    restart: "no"

  db:
    image: postgres:16-alpine
    container_name: postgres_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - network_dev

networks:
  network_dev:
